language: python
sudo: false

notifications:
  email: false

python:
  - 2.7
  - 3.5

env:
  - JUPYTER_VERSION="4.*"
  - JUPYTER_VERSION="5.*"
  - OS_AUTH_URL = https://keystone.ecdf.ed.ac.uk/v3
  - OS_PROJECT_ID = 0edbdcab2cda436a90ab73a26b77c83e
  - OS_PROJECT_NAME = edina  
  - OS_REGION_NAME = edina 
  - OS_USER_DOMAIN_NAME = ed 
  - OS_USERNAME = jupyter
  - OS_PASSWORD = edina123
  - OS_IDENTITY_API_VERSION = v3 
  - OS_INTERFACE = public
      
before_install:
  - pwd
  - source .ci/install_go.sh
  - source .ci/install_python.sh
  - source .ci/start_minio.sh

install:
  - pip install .

script:
  - py.test -s -vv --cov=s3contents --cov-report term-missing

after_success:
  - coveralls
